moved dep check prior to unshare

diff --git a/alpine-make-oci b/alpine-make-oci
--- a/alpine-make-oci
+++ b/alpine-make-oci
@@ -62,6 +62,13 @@ cleanup() {
     bad_args
 }
 
+# Check for required commands.
+for cmd in "$BUILDAH" "$TAR" $ALPINE_MAKE_ROOTFS; do
+    if ! command -V "$cmd" >/dev/null 2>&1; then
+        die "$cmd command missing."
+    fi
+done
+
 # Check if we should re-run this script using cgroup isolation.
 if [ "$1" = "unshare" ]; then
     shift
@@ -82,13 +89,6 @@ while :; do
         break
         ;;
     esac
-done
-
-# Check for required commands.
-for cmd in "$BUILDAH" "$TAR" $ALPINE_MAKE_ROOTFS; do
-    if ! command -V "$cmd" >/dev/null 2>&1; then
-        die "$cmd command missing."
-    fi
 done
 
 # Get the destination path.
